[general]
import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 500
