configpath: /home/shawn/.config/nom/config.yml
showfavourites: false
version: ""
feeds:
    - url: https://news.ycombinator.com/rss
      name: HN
    - url: https://lwn.net/headlines/newrss
      name: LWN
    - url: https://feeds.feedburner.com/codinghorror
      name: Coding Horror
    - url: https://feedx.net/rss/ap.xml
      name: AP
    - url: https://www.nobsbitcoin.com/rss/
      name: NoBSB
theme:
    glamour: dark
    titleColor: "170"
    filterColor: '#494d64'
    selectedItemColor: "110"
http:
    mintls: TLS 1.2
