configpath: /home/shawn/.config/nom/config.yml
showfavourites: false
version: ""
feeds:
    - url: https://news.ycombinator.com/rss
      name: HN
    - url: https://lwn.net/headlines/newrss
      name: LWN
    - url: https://feeds.feedburner.com/codinghorror
      name: Coding Horror
    - url: https://news.google.com/rss/search?q=site%3Areuters.com&hl=en-US&gl=US&ceid=US%3Aen 
      name: Reuters
    - url: https://www.nobsbitcoin.com/rss/
      name: NoBSB
    - url: https://xkcd.com/atom.xml
      name: xkcd
    - url: http://feeds.feedburner.com/oatmealfeed
      name: Oatmeal
    - url: http://rss.slashdot.org/Slashdot/slashdot
      name: Slashdot
theme:
    glamour: dark
    titleColor: "170"
    filterColor: '#494d64'
    selectedItemColor: "110"
http:
    mintls: TLS 1.2
